@startuml 画面遷移
    hide circle
    skinparam linetype ortho
    left to right direction

    entity "ログイン画面" as login {
        * ユーザーID
        * パスワード
    }

    entity "管理画面" as admin {
        * 出欠情報
        * 各種設定画面
        * クルーシフト情報
        * 請求画面
    }

    entity "クルーメイン画面" as crew {
        * シフト提出
        * シフト修正申請
        * 出退勤時刻登録
        * 有給休暇申請
        * 支払通知書承認
        * 請求書発行
        * 日報登録
        * 過去の出勤日数情報などの実績
    }

    entity "各種設定" as config {
        * シフト種別設定
        * 元請企業情報設定
        * 自社企業情報設定
        * クルー情報設定
    }

    entity "シフト種別設定" as attendance {
        * シフト種別　種別は限られてるからいらないかもしれない
    }

    entity "元請企業情報設定" as prime_conductor {
        * 企業名
        * 場所
        * 郵便番号
        * 住所
        * 電話番号
        * 登録番号
        * 代表名
        * 担当者名
        * 口座情報
        * 単価
        * 個建種別
    }

    entity "自社企業情報設定" as my_comp {
        * 企業名
        * 代表者名
        * 郵便番号
        * 住所
        * 電話番号
        * 登録番号
        * 口座情報
    }

    entity "クルー情報設定" as crew_info {
        * 名前
        * ID
        * パスワード
        * 場所
        * 郵便番号
        * 住所
        * 電話番号
        * 登録番号
        * 口座情報
        * 担当企業一覧
    }

    entity "請求画面" as payment {
        * 元請請求一覧
        * クルー支払通知一覧
        * クルー請求一覧
    }

    entity "クルーシフト情報" as shift {
        * シフト調整
        * 出退勤時間
        * メモ
        * 個建実績
    }

    entity "収支情報" as BOP {
        * 売上
        * 利益
        * 経費
        * その他収支情報
    }

    login --> admin :"管理者"
    login --> crew :"クルー"
    admin --> config
    admin --> payment
    admin --> shift
    admin --> BOP
    config --> attendance
    config --> prime_conductor
    config --> my_comp
    config --> crew_info
    shift --> payment
@enduml
