@startuml 画面遷移
    hide circle
    skinparam linetype ortho

    entity "管理画面" as admin {
        * クルー一覧
        * クルー申請
        --
        トップバー
        * シフト種別設定
        * 元請企業情報設定
        * 自社企業情報設定
        * クルー情報設定
        * クルーシフト情報
        * 請求画面
    }

    entity "シフト種別設定" as attendance {
        * シフト種別
        --
        選択肢があるだけでそれを有効無効で切り替え
    }

    entity "元請企業一覧" as prime_init {
        * 一覧表示
        * 新規作成
        * 編集
        * 削除
    }

    entity "元請企業情報設定" as prime_conductor {
        * 企業名
        * 場所
        * 郵便番号
        * 住所
        * 電話番号
        * 登録番号
        * 代表名
        * 担当者名
        * 口座情報
        * 単価
        * 個建種別
    }

    entity "自社企業情報設定" as my_comp {
        * 企業名
        * 代表者名
        * 郵便番号
        * 住所
        * 電話番号
        * 登録番号
        * 口座情報
        --
        編集のみ
    }

    entity "クルー情報一覧" as crew_init {
        * 一覧表示
        * 新規作成
        * 編集
        * 削除
    }

    entity "クルー情報設定" as crew_info {
        * 名前
        * ID
        * パスワード
        * 場所
        * 郵便番号
        * 住所
        * 電話番号
        * 登録番号
        * 口座情報
        * 担当企業一覧
    }

    entity "請求画面" as payment {
        * 元請請求一覧
        * クルー支払通知一覧
        * クルー請求一覧
    }

    entity "クルーシフト情報" as shift {
        * シフト調整
        * 出退勤時間
        * メモ
        * 個建実績
    }

    entity "収支情報" as BOP {
        * 売上
        * 利益
        * 経費
        * その他収支情報
    }

    entity "クルーメイン画面" as crew {
        * 出退勤時刻登録
        * 各種申請
        * 請求書
        * 実績情報
    }

    entity "シフト提出画面" as submit {
        * シフト提出
        * シフト修正申請
    }

    entity "各種申請" as application {
        * 有給休暇申請
    }

    entity "請求書" as invoice {
        * 支払通知書承認
        * 請求書、支払請求書一覧
    }

    entity "実績情報" as achievements {
        * 出退勤情報
        * 労働時間
        * 配達実績
    }

    admin --> payment
    admin --> shift
    admin --> BOP
    admin --> attendance
    admin --> prime_init
    admin --> my_comp
    admin --> crew_init
    prime_init --> prime_conductor
    crew_init --> crew_info
    shift --> payment
    crew --> submit
    crew --> application
    crew --> invoice
    crew --> achievements
@enduml
