@startuml DB_List
  hide circle
  skinparam linetype ortho

  package ユーザー関連 <<rectangle>> {
    entity "AdminUser システム管理者" as admin_users {
      * id : integer
      * login : string : ログインID
      --
      * password_digest : string : パスワード
      * name : string : ユーザー名
      current_log_in_at : datetime : ログイン日時
      last_log_in_at : datetime : 最後のログイン日時
    }

    entity "SalesAgent 販売代理店" as sales_agents {
      * id : integer
      * login : string : ログインID
      --
      * password_digest : string : パスワード
      * is_initial_password : boolean(true) : 初回ログインかどうか
      * name : string : ユーザー名
      current_log_in_at : datetime : ログイン日時
      last_log_in_at : datetime : 最後のログイン日時
    }

    entity "ServiceProvider 運送管理者" as service_providers {
      * id : integer
      * sales_agent : reference : 販売代理店
      * login : string : ログインID
      --
      * password_digest : string : パスワード
      * is_initial_password : boolean(true) : 初回ログインかどうか
      * company_name : string : 企業名
      * representative : string : 代表者名
      zipcode : string : 郵便番号
      address1 : string : 所在地1
      address2 : string : 所在地2
      regist_number : string : 登録番号
      phone : string : 電話番号
      fax : string : FAX
      email : string : メールアドレス
      shift_submission_deadline : integer : シフト提出の締日
      current_log_in_at : datetime : ログイン日時
      last_log_in_at : datetime : 最後のログイン日時
    }

    entity "ServiceManager 運送管理マネージャー" as service_managers {
      * id : integer
      * service_providers : reference : 運送管理者
      * login : string : ログインID
      --
      * password : string : パスワード
      * name : string : ユーザー名
      email : string : メールアドレス
      current_log_in_at : datetime : ログイン日時
      last_log_in_at : datetime : 最後のログイン日時
    }

    entity "Crew　クルー" as crews {
      * id : integer
      * service_providers : reference : 運送管理者
      * login : string : ログインID
      --
      * password : string : パスワード
      * name : string : ユーザー名
      zipcode : string : 郵便番号
      address1 : string : 所在地1
      address2 : string : 所在地2
      regist_number : string : 登録番号
      phone : string : 電話番号
      fax : string : FAX
      email : string : メールアドレス
      max_days_off : integereger : 申請可能最大休暇日数
      current_log_in_at : datetime : ログイン日時
      last_log_in_at : datetime : 最後のログイン日時
      * is_deleted : boolean(false) : 退職したかどうか
    }
  }

  package 銀行 <<rectangle>> {
    entity "Bank　銀行" as banks {
      * id : integer
      * billable : references
      --
      * name : string : 銀行名
      * branch_number : string : 支店コード
      * branch_name : string : 支店名
      * account_type : integereger : 口座種別
      * account_number : string : 口座番号
      * account_name : string : 口座名
    }
  }

  package 元請企業関連 <<rectangle>> {
    entity "Contractor　元請企業" as contractors {
      * id : integer
      * service_providers : reference : 運送管理者
      --
      * name : string : 元請企業名
      * display_name : string : 表示する企業名
      representative : string : 代表者名
      zipcode : string : 郵便番号
      address1 : string : 所在地1
      address2 : string : 所在地2
      regist_number : string : 登録番号
      phone : string : 電話番号
      email : string : メールアドレス
    }

    entity "WareHouse　倉庫" as ware_houses {
      * id : integer
      * contractors : reference : 元請企業
      --
      * name : string : 倉庫名
    }

    entity "Wage　単価" as wages {
      * id : integer
      * warehouse : reference : 倉庫
      --
      * wage_type : integereger : 給与種別
      * in_wage : float : 社内単価
      * ex_wage : float : 元請単価
    }

    entity "Package　個建" as packages {
      * id : integer
      * contractors : reference : 元請企業
      --
      * type_name : string : 個建名
    }

    entity "PackageUnitPrice　個建単価" as package_unit_prices {
      * id : integer
      * packages : reference : 個建
      --
      * wage_type : integereger : 給与種別
      * in_wage : float : 社内単価
      * ex_wage : float : 元請単価
    }

    entity "Assignment　CrewとWareHouseを関連付けるテーブル" as assignments {
      * id : integer
      * crew_id : integereger : クルーID
      * warehouse_id : integer : 倉庫ID
      --
      * is_primary : boolean : メインの担当かどうかを表すフラグ
    }

    entity "DeliveryArea　配達エリア" as delivery_areas {
      * id : integer
      * contractors : reference : 元請企業
      --
      name : string : コース名
    }
  }

  package 請求書関連 <<rectangle>> {
    entity "Invoice　請求書" as invoices {
      * id : integer
      * invoice_issuable : references
      * issue_date : date : 発行日
      due_date : date : 支払期限
      * invoice_number : string : 請求書番号
      * subject_yearmonth : date : 請求書の対象年月
      --
      remarks : text : 備考
      * is_tax_included : boolean(false) : 税込税抜
      subject : string : 件名
      amount : float : 合計請求金額
    }

    entity "BillingInfo　請求書宛先" as billing_infos {
      * id : integer
      * invoice : references : 請求書
      --
      company_name : string : 会社名
      contact_person : string : 担当者名
      zipcode : string : 郵便番号
      address1 : string : 住所1
      address2 : string : 住所2
    }

    entity "SenderInfo　請求書送り主" as sender_infos {
      * id : integer
      * invoice : references : 請求書
      --
      company_name : string : 企業名
      zipcode : string : 郵便番号
      address1 : string : 所在地1
      address2 : string : 所在地2
      phone : string : 電話番号
      fax : string : FAX
      regist_number : string : 登録番号
      contact_person : string : 担当者名
    }

    entity "BillingItem　品目" as billing_items {
      * id : integer
      * invoice : references : 請求書
      --
      name : string : 品目名
      quantity : float : 数量
      unit : string : 単位
      unit_price : float : 単価
      tax_rate : float : 税率
    }
  }

  package "PDF共有関連" <<rectangle>> {
    entity "SharedLink PDF共有" as shared_links {
      * id : integer
      * sharable : references : 共有
      * token : string : トークン
      --
      * is_public : boolean(true) : 公開するかしないか
    }
  }

  package 支払通知関連 <<rectangle>> {
    entity "PaymentNotification　支払ステータス" as payment_notifications {
      * id : integer
      * crew : references : クルー
      yearmonth : date : 支払対象年月
      --
      * status : integer : 支払状況
      notification_num : string : 支払通知書番号
    }
  }

  package シフト管理関連 <<rectangle>> {
    entity "ShiftPreference　シフト希望" as shift_preferences {
      * id : integer
      * crew : references : クルー
      * sdate : date : シフトの日付
      --
      * shift_type : integer : 稼働するかしないか
      * is_submitted : boolean(false) : 提出済か
      remarks : text : 備考
    }

    entity "Shift　シフト" as shifts {
      * id : integer
      * crew : references : クルー
      * sdate : date : シフトの日付
      * is_fixed : boolean(false) : 確定済か
      ware_house : references : 倉庫名
      --
      remarks : text : 備考
    }

    entity "ShiftDeriveryArea　シフトと配達地域" as shifts_delivery_areas {
      * id : integer
      * shift_id : integer : シフトテーブルのID
      * delivery_area_id : integer : 配達地域テーブルのID
      --
    }

    entity "DayOff　休暇" as day_offs {
      * id : integer
      * crew : references : クルー
      * sdate : date : 休暇日
      * is_fixed : boolean(false) : 確定済か
      --
      remarks : text : 備考
    }

    entity "DeliveryResult　配達実績" as delivery_results {
      * id : integer
      * tdate : date : 配達日
      * package_type : references : 個建種類
      --
      amount : integer : 配達個数
    }
  }

  package 出退勤関連 <<rectangle>> {
    entity "Attendance　出退勤" as attendances {
      * id : integer
      * crew : references : クルー
      * ware_house : references : 倉庫名
      shift : references : シフト
      --
      * checkin_time : datetime : 出勤時刻
      * checkout_time : datetime : 退勤時刻
      remarks : text : 備考
    }

    entity "DeliveryActualResult　配達参考値" as delivery_actual_results {
      * id : integer
      * attendace : references : 出欠
      * package_type : references : 個建種類
      --
      amount : integer : 配達個数
    }
  }

  sales_agents ||--|{ service_providers
  service_providers ||--|{ service_managers
  service_providers ||--|{ crews
  service_providers ||-l-|{ contractors
  contractors ||--|{ ware_houses
  contractors ||--|{ packages
  contractors ||--|{ delivery_areas
  invoices ||--|| billing_infos
  invoices ||--|| sender_infos
  invoices ||--|{ billing_items
  crews ||-d-|{ shift_preferences
  crews ||-d-|{ shifts
  ware_houses ||--|{ shifts
  delivery_areas ||--|{ shifts
  crews ||-d-|{ day_offs
  crews ||-d-|{ payment_notifications
  crews ||-d-|{ attendances
  ware_houses ||-l-|{ attendances
  shifts ||--|| attendances
  attendances ||--|{ delivery_actual_results
  shifts ||-u-|| shifts_delivery_areas
  delivery_areas ||--|| shifts_delivery_areas
  crews ||--|| assignments
  ware_houses ||-u-|| assignments
  ware_houses ||--|{ wages
  packages ||--|{ package_unit_prices

  payment_notifications ||..|| invoices
  invoices ||.r.|{ contractors


@enduml
